### ISSUE TITLE
Refresh token not working when Token is expired

### ISSUE THREAD

**Issue by bernardphua** [fullstackhero/blazor-starter-kit#106]
I'm rewriting this issue here again because my previous findings may not be correct. To simulate this issue I set the JWT Token to expire in 2 minutes in order to test the refresh token.

![image](https://user-images.githubusercontent.com/46226572/119121173-af431280-ba5f-11eb-8e52-04fbb9ee416f.png)

Run the application and Login using the default mukesh@blazorhero.com  account. Wait for about 3 to 5 minutes then click on any menu item e.g.  "User",  the application will failed and you are forced logout and redirect to the login screen. Since the RefreshToken is valid for 7 days, the application should be able to get a new JWT Token instead of crashing out. See screen shots below. 

![image](https://user-images.githubusercontent.com/46226572/119123444-25e10f80-ba62-11eb-98a8-a5f81ea8859d.png)
   
 
```
dotnet.5.0.6.js:1 POST https://localhost:5001/api/identity/token/refresh net::ERR_HTTP2_PROTOCOL_ERROR 500
dotnet.5.0.6.js:1 POST https://localhost:5001/api/identity/token/refresh net::ERR_HTTP2_PROTOCOL_ERROR 500
dotnet.5.0.6.js:1 GET https://localhost:5001/api/identity/user 500
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: 'M' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
System.Text.Json.JsonException: 'M' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'M' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorHero.CleanArchitecture.Shared.Wrapper.Result`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], BlazorHero.CleanArchitecture.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1[[BlazorHero.CleanArchitecture.Shared.Wrapper.Result`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], BlazorHero.CleanArchitecture.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Result`1](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[Result`1](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[Result`1](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[Result`1](String json, JsonSerializerOptions options)
   at BlazorHero.CleanArchitecture.Client.Infrastructure.Extensions.ResultExtensions.<ToResult>d__0`1[[System.Collections.Generic.List`1[[BlazorHero.CleanArchitecture.Application.Responses.Identity.UserResponse, BlazorHero.CleanArchitecture.Application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture.Client.Infrastructure\Extensions\ResultExtensions.cs:line 14
   at BlazorHero.CleanArchitecture.Client.Infrastructure.Managers.Identity.Users.UserManager.GetAllAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture.Client.Infrastructure\Managers\Identity\Users\UserManager.cs:line 24
   at BlazorHero.CleanArchitecture.Client.Pages.Identity.Users.GetUsersAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture\Client\Pages\Identity\Users.razor.cs:line 26
   at BlazorHero.CleanArchitecture.Client.Pages.Identity.Users.OnInitializedAsync() in C:\Users\admin\Documents\Source\BlazorHero\CleanArchitecture\BlazorHero.CleanArchitecture\Client\Pages\Identity\Users.razor.cs:line 21
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```

**Comment by unchase** [comment]
Hi, @bernardphua 
The error occurs in:

https://github.com/blazorhero/CleanArchitecture/blob/31324c50687240e3ea0cd30723941be53c694dcb/BlazorHero.CleanArchitecture.Client.Infrastructure/Managers/Identity/Authentication/AuthenticationManager.cs#L82-L85

when trying to call (`POST "/api/identity/token/refresh`):

https://github.com/blazorhero/CleanArchitecture/blob/31324c50687240e3ea0cd30723941be53c694dcb/BlazorHero.CleanArchitecture/Server/Controllers/Identity/TokenController.cs#L29-L30

First of all, should replace `new TokenResponse` to `RefreshTokenRequest` in this line:

https://github.com/blazorhero/CleanArchitecture/blob/31324c50687240e3ea0cd30723941be53c694dcb/BlazorHero.CleanArchitecture.Client.Infrastructure/Managers/Identity/Authentication/AuthenticationManager.cs#L82

Although this does not solve the issue.

---

The same problem see there: https://github.com/dotnet/aspnetcore/issues/20285

---

@iammukeshm Can you see what the problem might be?

**Comment by unchase** [comment]
I am tried to use:
`var response = await _httpClient.PostAsJsonAsync(Routes.TokenEndpoints.Refresh, new RefreshTokenRequest { Token = token, RefreshToken = refreshToken });` 

The same error occurs. May be the issue related to the CORS?

**Comment by bernardphua** [comment]
Hi @unchase , 

Thanks for looking into this issue. I have tried to make the changes you suggested in [2ac3210 ](https://github.com/unchase/CleanArchitecture-1/commit/2ac32105d684e1034fafb306e40fb534f6fcdf5b) but the problem still persist. Is it working over at your side?

**Comment by unchase** [comment]
> Hi @unchase ,
> 
> Thanks for looking into this issue. I have tried to make the changes you suggested in [2ac3210 ](https://github.com/unchase/CleanArchitecture-1/commit/2ac32105d684e1034fafb306e40fb534f6fcdf5b) but the problem still persist. Is it working over at your side?

Yes, it works for me. Did you add the CORS in `Startup.cs`?

**Comment by bernardphua** [comment]
> > Hi @unchase ,
> > Thanks for looking into this issue. I have tried to make the changes you suggested in [2ac3210 ](https://github.com/unchase/CleanArchitecture-1/commit/2ac32105d684e1034fafb306e40fb534f6fcdf5b) but the problem still persist. Is it working over at your side?
> 
> Yes, it works for me. Did you add the CORS in `Startup.cs`?

Hi @unchase ,
Yes, I did include the CORS in 'Startup.cs' but still getting the same error. Did you set the token to expire in 2 mins to test because the default is 2 days? I also notice others are getting the same error in #131

**Comment by unchase** [comment]
Hi, @bernardphua 
I even setted 1.5 minutes. No errors occur, including with status (#131).

**Comment by bernardphua** [comment]
Hi @unchase 
I refresh the latest codes from GitHub and only change the Token expire time to 1.5min. Run the application and after login wait for about 3mins before click on other menu item. I get the same error. Not sure why.

**Set Token to expire in 1.5 min**
![image](https://user-images.githubusercontent.com/46226572/120094012-6b7f9580-c150-11eb-9295-1daf8e7803b3.png)

**Get the same error as #131** 
![image](https://user-images.githubusercontent.com/46226572/120094123-13955e80-c151-11eb-874c-37fe886b3426.png)

**User forced logout with error**
![image](https://user-images.githubusercontent.com/46226572/120094038-9538bc80-c150-11eb-8feb-dcb42bfe74f0.png)

**Comment by unchase** [comment]
@iammukeshm reopen the issue, please

It is not resolved yet.

**Comment by supermun** [comment]
@unchase 
I've to bypass action when authentication failed:
**OnAuthenticationFailed = context => { return Task.CompletedTask; }**

like this link: [(https://github.com/iammukeshm/CleanArchitecture.WebApi/issues/32)]
