### ISSUE TITLE
Exception from AuthenticationHeaderHandler

### ISSUE THREAD

**Issue by justSteve** [fullstackhero/blazor-starter-kit#228]
**Describe the bug**
Several account-related actions will fire the SendAsync method from the  AuthenticationHeaderHandler class. When the action is an attempt to log-in (using either of the 2 supplied accounts) the debugger output will record the exception pasted below. Other actions (such as editing profile) will not toss any exception messages. Despite the fact that an exception is recorded, the attempt to login is successful. No visible malfunction is observed.

**To Reproduce**
1. Follow the 'getting started' instructions.
2. Debug (run) the app. The 'Sign In' screen is displayed.
3. Use either of the 'Fill credentials' links.
4. Review VS's debug output window.

**Expected behavior**
Is the posted exception message a 'false positive' and can be ignored? No malfunction is observed -- access is granted and honors User vs. Admin roles. Editing a profile works as expected.

**Screenshots**
`crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Eventinars.Client.Infrastructure.Authentication.AuthenticationHeaderHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in S:\foo\src\Client.Infrastructure\Authentication\AuthenticationHeaderHandler.cs:line 31
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Toolbelt.Blazor.HttpClientInterceptorHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Toolbelt.Blazor.HttpClientInterceptorHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Eventinars.Client.Infrastructure.Managers.Identity.Account.AccountManager.GetProfilePictureAsync(String userId) in S:\foo\src\Client.Infrastructure\Managers\Identity\Account\AccountManager.cs:line 33
   at Eventinars.Client.Shared.Components.UserCard.LoadDataAsync() in S:\foo\src\Client\Shared\Components\UserCard.razor.cs:line 36
   at Eventinars.Client.Shared.Components.UserCard.OnInitializedAsync() in S:\foo\src\Client\Shared\Components\UserCard.razor.cs:line 20
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
`

**Comment by Beauty-Kumari** [comment]
I am also facing the same issue since last 25 days.
Have you got any solution?

**Comment by Beauty-Kumari** [comment]
I am also facing the same issue since last 25 days.
#justSteve Have you got any solution?

**Comment by nbiada** [comment]
Hi all,
look at my PR https://github.com/blazorhero/CleanArchitecture/pull/271 and comment in this issue https://github.com/blazorhero/CleanArchitecture/issues/263

**Comment by justSteve** [comment]
Solved by nbiada's #263.
