### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by cuban8IO** [fullstackhero/blazor-starter-kit#87]
Hi,
i've created the this template via nuget comand "dotnet new BlazorHero.CleanArchitecture"
I starting the server with .net console (not IIS). All builds fine but the console writes some exceptions:
I have not changed anything yet. 
How can I fix these errors?
Thanks! 

``
Sending HTTP request GET https://localhost:5001/api/identity/account/profile-picture/c6feb5e1-61e6-426a-9117-e3d253ef1dab
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Demo.Client.Infrastructure.Authentication.AuthenticationHeaderHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\code\private\Demo\Demo.Client.Infrastructure\Authentication\AuthenticationHeaderHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Toolbelt.Blazor.HttpClientInterceptorHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Toolbelt.Blazor.HttpClientInterceptorHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Demo.Client.Infrastructure.Managers.Identity.Account.AccountManager.GetProfilePictureAsync(String userId) in C:\code\private\Demo\Demo.Client.Infrastructure\Managers\Identity\Account\AccountManager.cs:line 33
   at Demo.Client.Shared.Components.UserCard.LoadDataAsync() in C:\code\private\Demo\Demo\Client\Shared\Components\UserCard.razor.cs:line 36
   at Demo.Client.Shared.Components.UserCard.OnInitializedAsync() in C:\code\private\Demo\Demo\Client\Shared\Components\UserCard.razor.cs:line 20
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: TypeError: Failed to fetch
System.Net.Http.HttpRequestException: TypeError: Failed to fetch
   at System.Net.Http.BrowserHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Demo.Client.Infrastructure.Authentication.AuthenticationHeaderHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\code\private\Demo\Demo.Client.Infrastructure\Authentication\AuthenticationHeaderHandler.cs:line 30
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Toolbelt.Blazor.HttpClientInterceptorHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Toolbelt.Blazor.HttpClientInterceptorHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Demo.Client.Infrastructure.Managers.Identity.Account.AccountManager.GetProfilePictureAsync(String userId) in C:\code\private\Demo\Demo.Client.Infrastructure\Managers\Identity\Account\AccountManager.cs:line 33
   at Demo.Client.Shared.Components.UserCard.LoadDataAsync() in C:\code\private\Demo\Demo\Client\Shared\Components\UserCard.razor.cs:line 36
   at Demo.Client.Shared.Components.UserCard.OnInitializedAsync() in C:\code\private\Demo\Demo\Client\Shared\Components\UserCard.razor.cs:line 20
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
Debugging hotkey: Shift+Alt+D (when application has focus)
[0m[48;5;127m[38;5;231mblazor[0m[1m Loaded 12.36 MB resources
[0mThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.[0m
Loaded 12.36 MB resources from cache
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      ClaimsAuthorizationRequirement:Claim.Type=Permission and Claim.Value is one of the following values: (Permissions.Roles.View)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      ClaimsAuthorizationRequirement:Claim.Type=Permission and Claim.Value is one of the following values: (Permissions.Users.View)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      ClaimsAuthorizationRequirement:Claim.Type=Permission and Claim.Value is one of the following values: (Permissions.Products.View)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      ClaimsAuthorizationRequirement:Claim.Type=Permission and Claim.Value is one of the following values: (Permissions.Brands.View)
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
``

**Comment by Duelbat** [comment]
Was the create command complete ?  "dotnet new BlazorHero.CleanArchitecture -n NameOfProject "

**Comment by iammukeshm** [comment]
could you try to run the application in a different browser? maybe without caching?

**Comment by cuban8IO** [comment]
Hi,
sorry for my late answer. 
@Duelbat  yes. this was the complete command. I used the steps in the documentation.

@iammukeshm  I've testet on Firefox and Chrome as well. The same issue. I also testet with incognito tab.

The issue comes only with .net hostet console app. In IIS-Express works fine. But i become a JSinterOp Exception from MudBlazor on pciture upload...

**Comment by DanPFW** [comment]
I've just tried creating a new projectc from the template, as well as downloaded the repo directly, and get this error trying to run the site after successful compilcation.  This is at the logon screen.

Failed to load resource: the server responded with a status of 404 ()
blazor.webassembly.js:1 info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]
      Authorization failed. These requirements were not met:
      DenyAnonymousAuthorizationRequirement: Requires an authenticated user.
blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Response status code does not indicate success: 404 (Not Found).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.GetNegotiationResponseAsync(Uri uri, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.SelectAndStartTransport(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsyncCore(TransferFormat transferFormat, CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.StartAsync(TransferFormat transferFormat, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnectionFactory.ConnectAsync(EndPoint endPoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncCore(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsyncInner(CancellationToken cancellationToken)
   at System.Threading.Tasks.ForceAsyncAwaiter.GetResult()
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.StartAsync(CancellationToken cancellationToken)
   at BlazorHero.CleanArchitecture.Client.Shared.MainLayout.OnInitializedAsync() in C:\Users\e99444\Documents\GitHub\CleanArchitecture\BlazorHero.CleanArchitecture\Client\Shared\MainLayout.razor.cs:line 61
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
